name: Repository Dispatch
on:
  repository_dispatch:
    types: [start-check]
jobs:
  myEvent:
    runs-on: ubuntu-latest
    steps:
      ####################################################
      # Update the status to show that the queued message
      # was received and is being processed
      ####################################################
      - name: Acknowledge Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'status=in_progress' \
            /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }}    
