name: WAT
on:
  pull_request:
jobs:

  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Create Check Run
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RESPONSE=$(gh api -X POST -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f name='Tests' \
              -f head_sha='${{ github.sha }}' \
              /repos/${{ github.repository }}/check-runs)
              
          PR_ID=$(echo "$RESPONSE" | jq -r '.pull_requests[0].number')
          BRANCH_NAME=$(echo "$RESPONSE" | jq -r '.pull_requests[0].head.ref')
      - name: Call Codeception Cloud
        run: |
          curl -X POST https://codeception.cloud/api/environments \
            -H "Content-Type: application/json" \
            -d '{
              "branch_name": "'$BRANCH_NAME'",
              "pr_number": "'$PR_ID'"
            }'
