name: WAT
on:
  pull_request:
jobs:

  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Create Check Run & Call Codeception Cloud
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          RESPONSE=$(gh api -X POST -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f name='Tests' \
              -f head_sha='${{ github.event.pull_request.head.sha }}' \
              /repos/${{ github.repository }}/check-runs)
              
          PR_ID=$(echo "$RESPONSE" | jq -r '.pull_requests[0].number')
          BRANCH_NAME=$(echo "$RESPONSE" | jq -r '.pull_requests[0].head.ref')

          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://codeception.cloud/api/environments \
            -H "Content-Type: application/json" \
            -d '{
              "branch_name": "'$BRANCH_NAME'",
              "pr_number": "'$PR_ID'"
            }')

          echo "Check run created with branch $BRANCH_NAME and PR number $PR_ID (HTTP code: $HTTP_CODE)"

          

          
          
