name: WAT

on:
  pull_request:

jobs:
  Init:
    runs-on: ubuntu-latest
    steps:
      - name: Call Codeception Cloud & Create Check Run if 204
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # Appel à l'API Codeception Cloud
          PR_ID=$(echo "${{ github.event.pull_request.number }}")
          BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}")

          # Appel API Codeception Cloud et capture du code HTTP
          HTTP_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST https://codeception.cloud/api/environments \
            -H "Content-Type: application/json" \
            -d '{
              "branch_name": "'$BRANCH_NAME'",
              "pr_number": "'$PR_ID'"
            }')

          echo "HTTP response code from Codeception Cloud: $HTTP_CODE"

          # Si la réponse est 204, alors créer le check run
          if [ "$HTTP_CODE" -eq 204 ]; then
            echo "Codeception Cloud responded with 204, creating Check Run."

            RESPONSE=$(gh api -X POST -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f name='Tests' \
              -f head_sha='${{ github.event.pull_request.head.sha }}' \
              /repos/${{ github.repository }}/check-runs)

            CHECK_RUN_ID=$(echo "$RESPONSE" | jq -r '.id')
            echo "Check run created with ID: $CHECK_RUN_ID"
          else
            echo "Codeception Cloud did not respond with 204. No Check Run created."
          fi
