name: dummy-workflow
on:
  pull_request:
  repository_dispatch:
    types: [wat-started, wat-ended]
jobs:

  dummy-job:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Dummy Step
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          CHECKID=$(gh api -X POST -H "Accept: application/vnd.github+json" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              -f name='WAT' \
              -f head_sha='${{ github.event.pull_request.head.sha }}' \
              --jq '.id' \
              /repos/${{ github.repository }}/check-runs)
          echo "Dummy step started: $CHECKID"

  dummy-job-2:
    runs-on: ubuntu-latest
    if: github.event_name == 'wat-started'
    steps:
      - name: Dummy Step 2
        env:
          GH_TOKEN: ${{ github.token }}   
        run: |
          gh api -X PATCH -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -f 'status=in_progress' \
            /repos/${{ github.repository }}/check-runs/${{ github.event.client_payload.checkRunId }} 
    

